# Generated by Django 5.2.7 on 2025-11-16 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('tragedy', 'Трагедія'), ('comedy', 'Комедія'), ('farce', 'Фарс'), ('satire', 'Сатира'), ('mystery', 'Містерія'), ('historical', 'Історична вистава'), ('opera', 'Опера'), ('operetta', 'Оперета'), ('ballet', 'Балетна вистава'), ('circus', 'Циркова вистава'), ('monoplay', 'Вистава одного актора'), ('children', 'Дитяча вистава')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_performance_types', models.ManyToManyField(blank=True, related_name='users', to='users.performancetype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
