# Generated by Django 5.2.7 on 2025-10-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('preferred_performance_type', models.CharField(blank=True, choices=[('tragedy', 'Трагедія'), ('comedy', 'Комедія'), ('farce', 'Фарс'), ('satire', 'Сатира'), ('mystery', 'Містерія'), ('historical', 'Історична вистава'), ('opera', 'Опера'), ('operetta', 'Оперета'), ('ballet', 'Балетна вистава'), ('circus', 'Циркова вистава'), ('monoplay', 'Вистава одного актора'), ('children', 'Дитяча вистава')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
