# Generated by Django 5.2.7 on 2025-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('tragedy', 'Трагедія'), ('comedy', 'Комедія'), ('farce', 'Фарс'), ('satire', 'Сатира'), ('mystery', 'Містерія'), ('historical', 'Історична вистава'), ('opera', 'Опера'), ('operetta', 'Оперета'), ('ballet', 'Балетна вистава'), ('circus', 'Циркова вистава'), ('monoplay', 'Вистава одного актора'), ('children', 'Дитяча вистава')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_performance_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_performance_types',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.performancetype'),
        ),
    ]
