# Generated by Django 5.2.7 on 2025-11-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
    ]
