# Generated by Django 5.2.7 on 2025-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_genre_show_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
