# Generated by Django 5.2.7 on 2025-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_remove_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_per_row',
            field=models.IntegerField(default=1),
        ),
    ]
