# Generated by Django 5.2.7 on 2025-12-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_alter_seat_hall_alter_show_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='shows.hall'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.hall'),
        ),
    ]
