# Generated by Django 5.2.7 on 2025-12-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_seat'),
        ('shows', '0006_alter_seat_hall_alter_show_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shows.seat'),
            preserve_default=False,
        ),
    ]
